Update Pages section
decidim/documentation pull request #166
Opened 2024-11-06 17:46 UTC by paulinebessoles

#### :tophat: What? Why?
This PR is related to the documentation update. 

#### :tophat: Done

- [ ] Update Pages parent page
- [ ] Create Topics page
- [ ] Create Pages child page
- [ ] Update navigation
- [ ] Update screenshots

#### :pushpin: Related Issues
Issues: https://github.com/decidim/documentation/issues/165

#### Testing

:hearts: Thank you!

2024-11-20 10:11 UTC, carolromero requested changes
@paulinebessoles just left you a couple of comments for small changes.

2024-11-20 10:11 UTC, carolromero commented on docs/en/modules/admin/pages/pages/pages.adoc
> +* What are the terms of conditions and the legal information about this platform?
```suggestion
* What are the terms and conditions and the legal information about this platform?
```

2024-11-20 10:11 UTC, carolromero commented on docs/en/modules/admin/pages/pages/pages.adoc
> +You can manage the pages from this administration panel:
> 
```suggestion
You can manage the pages from this section of the administration panel: 
```

2024-11-21 15:18 UTC, paulinebessoles commented
@carolromero this PR is ready for new review and merde

2024-11-28 12:23 UTC, merged