Admin
decidim/documentation pull request #171
Opened 2024-11-14 14:31 UTC by paulinebessoles

#### :tophat: What? Why?
This PR is related to the documentation update. 

#### :tophat: Done

- [x] Move content from Introduction page
- [x] Update admin page
- [x] Update schema 

#### :pushpin: Related Issues

#### Testing

:hearts: Thank you!

2024-11-25 08:51 UTC, NilHomedes requested changes
I just add a comment about the spaces-components image

2024-11-25 08:51 UTC, NilHomedes commented on docs/en/modules/admin/assets/images/introduction.png
This image may lead to confusion, maybe? 
It seems that for Initiatives, you only can enable the debates component. We have two options:
- Adding all the narrows (which generates a very chaotic picture)
- Keeping he image without narrows, only showing the spaces and components

Or maybe explain better in the text that for each space you can enable all the components. 
From my point of view, it is important to avoid creating confusion.

2024-11-26 15:47 UTC, paulinebessoles commented on docs/en/modules/admin/assets/images/introduction.png
Yes, you are right, I deleted the narrows to only show spaces and components!

2024-11-26 15:58 UTC, paulinebessoles commented
@NilHomedes this PR is ready to be reviewed again

2024-11-27 08:40 UTC, NilHomedes approved these changes
Wonderful job @paulinebessoles ✨

2024-11-28 12:29 UTC, merged